version: '3.2'
 
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: tech-challenge-payment
    networks:
      - ambiente
  app:
    restart: always
    container_name: App
    build:
      context: .
    ports:
      - "8085:8083"
    environment:
      MONGO_HOST: mongodb
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      KAFKA_SERVERS: kafka:19092
    depends_on:
      - mongodb
      - kafka
    links:
      - mongodb
      - kafka
    networks:
      - ambiente
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - ambiente

    # https://hub.docker.com/r/confluentinc/cp-kafka/
  kafka:
      container_name: kafka
      image: wurstmeister/kafka:2.12-2.2.1
      environment:
        ## the >- used below infers a value which is a string and properly
        ## ignore the multiple lines resulting in one long string:
        ## https://yaml.org/spec/1.2/spec.html

        KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
        KAFKA_LISTENERS: >-
          LISTENER_DOCKER_INTERNAL://:19092,
          LISTENER_DOCKER_EXTERNAL://:9092

        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
          LISTENER_DOCKER_INTERNAL:PLAINTEXT,
          LISTENER_DOCKER_EXTERNAL:PLAINTEXT

        KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_LOG4J_LOGGERS: >-
          kafka.controller=INFO,
          kafka.producer.async.DefaultEventHandler=INFO,
          state.change.logger=INFO
      ports:
        - 9092:9092
      depends_on:
        - zookeeper
      networks:
        - ambiente
networks: 
  ambiente:
    driver: bridge
