server:
  port: 8083
spring:
  application:
    name: tech-challenge-payment
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST}
      port:
      database: tech-challenge-payment
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
api:
  mercadolivre:
    url: https://api.mercadopago.com
    orders: instore/orders/qr/seller/collectors/1423020936/pos/DANICAIXA01/qrs
    token: TEST-7847449179180884-072110-5b05cf6195417ca341935a011741dbdb-1423020936
    payment: merchant_orders

kafka:
  topic:
    consumer:
      orders: tech.orders
      groupId: tech
    producer:
      payment: tech.payment

lanchonete:
  description: Lanchonete Tech Challenge, Lanches, Bebidas, Sobremesas
  title: Lanchonete Tech Challenge

swagger:
  title: Microserviço de Pagamentos
  contact:
    email: daniel.cor@outlook.com
    name: Daniel Aleixo Correa
    description: Microserviço desenvolvido para o curso de pós tech da FIAP
    version: 1.0

notification:
  url: