server:
  port: 8087
spring:
  application:
    name: tech-challenge-product
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: tech-challenge-payment
      username: root
      password: example
  kafka:
    bootstrap-servers: localhost:9092
api:
  mercadolivre:
    api:  https://api.mercadopago.com
    orders: instore/orders/qr/seller/collectors/1423020936/pos/DANICAIXA01/qrs
    token: TEST-7847449179180884-072110-5b05cf6195417ca341935a011741dbdb-1423020936
    payment: merchant_orders

kafka:
  topic:
    consumer:
      orders: tech.orders
      groupId: tech
    producer:
      payment: tech.payment
      error:
        payment: tech.error.payment

lanchonete:
  description: Lanchonete Tech Challenge, Lanches, Bebidas, Sobremesas
  title: Lanchonete Tech Challenge

notification:
  url: https://eogk4e0gy2wck7w.m.pipedream.net

time:
  expiration:
    payment: 1