apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: daniel36/tech-challenge-payment:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8083
          resources:
            limits:
              cpu: 0.2
              memory: "512Mi"
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config-map
                  key: mongo-host

            - name: MONGO_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config-map
                  key: mongo-username

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password

            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config-map
                  key: kafka-servers

