apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
spec:
  type: LoadBalancer
  selector:
    app: payment
  ports:
    - protocol: TCP
      name: http
      port: 8083
      targetPort: 8083
      nodePort: 30002